# Control mode of each motor can be set using this service.
#
# mode is control mode: 'free', 'position', 'speed', or 'torque'.
# The following abbreviations can also be used: 
#  'f', 'p', 's', 't', 'fre', 'pos', 'spd', 'trq'

uint8 id
string mode
---
bool success